# Generated by Django 4.2.5 on 2023-09-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassicCafeFeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=255)),
                ('feedback', models.TextField(blank=True, max_length=1000, null=True)),
                ('rate', models.CharField(choices=[('G', 'good'), ('Vg', 'very-good'), ('B', 'Bad'), ('Vb', 'very-bad')], default='G', max_length=2)),
            ],
        ),
    ]
